### ISSUE TITLE
Error in Morisita's formula

### ISSUE THREAD

**Issue by ctholley** [droglenc/FSAmisc#1]
https://github.com/droglenc/FSAmisc/blob/a0ea1e92cfc93c434956a3647b82d94eb8e88c50/R/dietOverlap.R#L150

In the denominator of the equation, the `(num1-1)*(N1-1)` and `(num2-1)*(N2-1)` should be divided not multiplied together.
For example: `doi <- (2*sum(prop1*prop2))/(sum(prop1*((num1-1)/(N1-1)))+sum(prop2*((num2-1)/(N2-1)))) `

**Comment by droglenc** [comment]
@ctholley Sorry for the delay. I have not worked with this repo in several years so it took a bit to bring it "up-to-speed" with the latest R and my other packages. I have made the change that you suggested on the latest GitHub version. Do you have any data and results from either hand calculations or other software that I can use to create a test that "my" function is producing the correct result?

Regardless ... thanks for forwarding the issue.

**Comment by ctholley** [comment]
@droglenc Thank you for responding to this issue and for developing this code. I understood that this function being included in FSAmisc meant that it had not been fully tested. Below is the process I went through to assess the Morisita’s index.

Ogle example data
```
ex.names <- c("bluegill","perch","minnows","bullheads","insects","zooplankton")
lmb <- c(55,35,23,7,3,1)
wae <- c(23,45,2,17,7,2)

#Continuation of first example with 'extra' info required for Morisita's index
#Hypothetical numbers of fish with each food item (occurrence)
num.lmb <- c(17,13,4,7,24,13)
num.wae <- c(37,12,23,8,9,13)

#Hypothetical total numbers of each predator
N.lmb <- 30
N.wae <- 40

overlap1 <- dietOverlap(lmb,wae,prey=ex.names,
                        type="Morisita",
                        num1=num.lmb,
                        num2=num.wae,
                        N1=N.lmb,
                        N2=N.wae)

summary(overlap1)
#The Morisita diet overlap index is 0.0005164.
#This value seems unnaturally low
```


Creating data to test formula
```
test.names <- c("Ephemeroptera", "Odonata", "Diptera")
set.seed(123)
speciesA <- sample(0:250, 3, replace=T) #158,206,178
speciesB <- sample(0:250, 3, replace=T) #13,194,169

N.speciesA <- 75
N.speciesB <- 90

num.speciesA <- sample(0:75, 3, replace=T) #49,42,13
num.speciesB <- sample(0:90, 3, replace=T) #24,89,90

overlap2 <- dietOverlap(speciesA, speciesB, prey=test.names,
                        type="Morisita",
                        num1=num.speciesA,
                        num2=num.speciesB,
                        N1=N.speciesA,
                        N2=N.speciesB)
summary(overlap2)
#The Morisita diet overlap index is 6.97e-05.
#This value also seems unnaturally low
```

Performing the Morisita's index calculation by hand
```
#Using the test data
set.seed(123)
speciesA2 <- sample(0:250, 3, replace=T) #158,206,178
speciesB2 <- sample(0:250, 3, replace=T) #13,194,169

prop1 <- c(speciesA2[1]/sum(speciesA2),
           speciesA2[2]/sum(speciesA2),
           speciesA2[3]/sum(speciesA2)
)

prop2 <- c(speciesB2[1]/sum(speciesB2),
           speciesB2[2]/sum(speciesB2),
           speciesB2[3]/sum(speciesB2)
)

num1 <- sample(0:75, 3, replace=T) #49,42,13
num2 <- sample(0:90, 3, replace=T) #24,89,90

N1 <- 75
N2 <- 90

#Original Morisita's index formula
(2*sum(prop1*prop2))/(sum(prop1*((num1-1)*(N1-1)))+sum(prop2*((num2-1)*(N2-1))))
#Result same as in the original dietOverlap function "6.96975e-05"

#Corrected Morisita's index formula
(2*sum(prop1*prop2))/(sum(prop1*((num1-1)/(N1-1)))+sum(prop2*((num2-1)/(N2-1))))
#New overlap index "0.4977763"

#Note: when using the lmb and wae example data with the corrected formula 
#the new overlap index value is 0.6106001
```

Sources for Morisita formula:

Morisita, M. (1959). Measuring of interspecific association and similarity 
between communities. Mem. Fac. Sci. Kyushu Univ. Ser. E (Biol.), 3, 65-80.

Krebs CJ. (2014). Ecological methodology, 3rd ed (in prep). 
URL: https://www.zoology.ubc.ca/~krebs/books.html
Chapter 14 URL: https://www.zoology.ubc.ca/~krebs/downloads/krebs_chapter_14_2021.pdf
Accessed: 07/22/2021

**Comment by droglenc** [comment]
@ctholley Thank you. I have reviewed this and added your example code (slightly modified) to the package as a test. The correction you suggested (and tested against your example hand-calculations) are in the latest version of `FSAmisc` on GitHub. Thanks again for your attention to this and your help with the solution.
